# Generated by Django 5.0.2 on 2024-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_remove_news_description_news_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('decs', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'страница "о нас"',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Новости'},
        ),
    ]
